### ISSUE TITLE
missing some operator

### ISSUE THREAD

**Issue by aster94** [SpenceKonde/ATTinyCore#183] opened 2017-12-12 22:02 UTC
hello dr Azzy,

i think that in your core there are "something" missing. the quotation marks are there because to  be honest i am not sure about what these things are

please see: https://forum.arduino.cc/index.php?topic=351930.0
i am using this library: https://github.com/0xPIT/encoder 
and it uses the "new" operator, it was missing so i added it with:

void *operator new(size_t size) {
  return malloc(size);
}

and it worked
i thought you would like to add these

**Comment by SpenceKonde** [comment] 2017-12-13 06:35
This is a duplicate of #169. It is fixed in the github version, but not yet in the board manager version.

**Closed by SpenceKonde** 2017-12-13 06:35 UTC

**Comment by aster94** [comment] 2017-12-13 08:00
Great to know that it is already fixed!
