### ISSUE TITLE
ATtiny85 1mhz Tone()

### ISSUE THREAD

**Issue by Hoshwan** [SpenceKonde/ATTinyCore#142] opened 2017-06-05 00:40 UTC
Can an attiny85 successfully run Tone() or TimerFreeTone() with a 1mhz clock?

I've actually been using the TimerFreeTone() library with the ATtiny85 which runs beautifully at 8mhz, but not 1mhz.

Different Attiny Cores I've used:

-arduino-tiny

-attiny by David A. Mellis

-ATTinyCore by Spence Kode

I've tried Tone() and TimerfreeTone() with all of the above mentioned cores and none of them work with a 1mhz clock.

Is it possible?

Thanks!

**Comment by SpenceKonde** [comment] 2017-06-05 00:44
Of course Tone() should work. I don't know why it doesn't. Do you have verified test code that is known to reproduce the issue? 

Are you repeatedly calling Tone() in a tight loop? Don't do that.  See #111

The cores other than ATTinyCore and the TimerfreeTone() library are beyond the scope of this repo.

**Comment by Hoshwan** [comment] 2017-06-05 01:10
It works! 
I haven't used Tone() in a while. I just needed to call the function properly. 

1mhz sounds terrible though as compared to 8mhz. (I am rebootloading to switch to the proper fuse setting)
FYI: Using the same core TimerFreeTone() is louder and clearer than Tone() both at 8mhz, but TimerFreeTone() won't work at 1mhz at all.

Any idea why 1mhz Tone() sounds so terrible?

**Comment by SpenceKonde** [comment] 2017-06-05 01:14
Would need to look at what you're seeing on a scope - are you using the recommended output pin? depending on the frequency, you might be pushing the limits of what the processor can due on a pin where it can't use hardware output compare.

**Comment by Hoshwan** [comment] 2017-06-05 01:38
Here's the code:

void setup() {
  tone(1, 2637);
}
void loop()
{
}


here's what the scope looks like:

![pico](https://cloud.githubusercontent.com/assets/22298171/26767419/c4b984d0-4954-11e7-9a57-aae44fad6a75.jpg)

**Comment by Hoshwan** [comment] 2017-06-05 01:40
here's the same image without the bottom cut off:
![pico2](https://cloud.githubusercontent.com/assets/22298171/26767484/4b52f49a-4955-11e7-850f-20386a1fc15f.jpg)

**Comment by SpenceKonde** [comment] 2017-06-05 02:54
That's strange... 

Do you get better results with pin 4? That should generally work way better for Tone because we can use hardware output compare there instead of interrupts.

**Comment by Hoshwan** [comment] 2017-06-05 06:28
Perfect!
That did it. Pin 4 produces a very clean tone. Too bad the proto PCB is already designed for use with pin 1.  No big deal though, that's what prototypes are for.

I wanted to get it working with a 1mhz clock (off the shelf Attiny85 setting) so the board house doesn't need to set the clock fuse before programming if it's not even necessary.

Digression:
Can you recommend resources for gaining a deeper understanding of AVR architecture and how to apply it? I've been playing with Atmel Studio and exploring using registers directly, but it feels like wading into a very deep ocean without direction or a life jacket.

Any advice you could offer would be appreciated.
Thanks.

**Comment by SpenceKonde** [comment] 2017-06-14 16:11
I gained my understanding of the AVR architecture (actually, stuff like this is more the on-chip peripherals common to AVR chips - not exactly the same thing as the architecture, but this is a matter of semantics) from the part datasheets, for the most part...  I haven't done much of anything with Atmel Studio - I use the IDE, or for a few projects, makefiles. 

The issues with Tone on other pins will be addressed in 1.1.4

**Comment by SpenceKonde** [comment] 2018-10-09 03:33
I couldn't reproduce the original issue. 

However. 1MHz tone did not work as documented. This has been fixed.

**Closed** 2018-10-09 03:32 UTC
Labels: bug
