### ISSUE TITLE
ATtiny43 ADC_TEMPERATURE should be 135

### ISSUE THREAD

**Issue by PaulZC** [SpenceKonde/ATTinyCore#595] opened 2021-07-27 13:23 UTC
Hi Spence,

Sincere thanks for all the time and effort you have put into this board package. It is a thing of beauty.

I found a gremlin in the ```pins_arduino.h``` for the ATtiny43. ```ADC_TEMPERATURE``` is defined as 34, but should be 135 (0x80 | 7):

https://github.com/SpenceKonde/ATTinyCore/blob/f5eabc8fb97e8fd72f1782a5e97345729e42ec47/avr/variants/tiny43/pins_arduino.h#L38

The CPU temperature sensor is connected to the ADC MUX channel 7 on the 43:

![image](https://user-images.githubusercontent.com/5690545/127160645-f5c6d8ef-17cc-4345-a35f-3ffad0a72c91.png)

OR'ing that with 0x80 gives the correct 'pin' number for ```analogRead```.

Very best wishes,
Paul

**Comment by SpenceKonde** [comment] 2021-07-27 14:15
Thanks... though as it happens, it is already fixed for 2.0.0 https://github.com/SpenceKonde/ATTinyCore/blob/v2.0.0-dev/avr/variants/tiny43/pins_arduino.h 

The problem is that 2.0.0 is not usable right now. I have the core itselfg mostly sorted, boards.txt needs to be completely rewritten. 
2.0.0 should be released in late 2020 (not a typo). 

I'm running a bit behind schedule, as you can see,

**Closed as completed by SpenceKonde** 2021-07-27 14:15 UTC
