### ISSUE TITLE
Allow analog pin names to be used with pinMode/digitalRead/digitalWrite on all processors

### ISSUE THREAD

**Issue by battosai30** [SpenceKonde/ATTinyCore#116] opened 2017-04-08 07:05 UTC
Hi,

I just observed an issue with Attiny84 (so I guess on 24/44 too) :

http://drazzy.com/e/img/PinoutT84a.jpg

When I select "Damellis core" pin mapping, I get clockwise pin mapping in reality (I did not check if the inverse is true).

**Comment by per1234** [comment] 2017-04-08 07:55
You didn't respond to the question I asked you on the other issue report(https://github.com/arduino/Arduino/issues/6160):
>It's not exactly clear to me what the issue you're reporting is. Are you saying that you think the label on the pinout diagram "Alternative pinout" for the "Counterclockwise (like ATTinyCore)" pin mapping is confusing as you would expect the "Clockwise (like damellis core)" pin mapping to be considered the "alternative"? It was [specifically decided](https://github.com/SpenceKonde/ATTinyCore/issues/50#issuecomment-202126223) that damellis mapping would be the "default", though that's also confusing since the ATTinyCore mapping is actually the default selection in the **Tools > Pin Mapping**.  It does seem like it would be more clear for the label on the diagram to match the text of the options in the **Tools > Pin Mapping** menu rather than using the vague term "Alternative pinout".

**Comment by battosai30** [comment] 2017-04-08 07:59
When I explicitly select AttinyCore pinMapping, I do not get it "in real" (I did not check at this moment if at this moment I got the damellisCore pinMapping). To get my circuit working, I had to select damellisCore pin mapping in arduino IDE, and use in my Arduino code the pins numbers of AttinyCore pin mapping.

**Comment by SpenceKonde** [comment] 2017-04-08 08:03
I haven't touched this in eons. Was this always broken?!

**Comment by battosai30** [comment] 2017-04-08 08:05
I think at least since this summer (I made another project based on attiny84 and I noticed this bug but I was very busy so did not noticed this issue on git)

**Comment by SpenceKonde** [comment] 2017-04-24 17:27
I think I fixed the default selection issue. 

However, I'm just staring at the files, and I can't understand how you're ending up with the wrong pin mapping... the files sure look correct...

**Comment by battosai30** [comment] 2017-04-24 17:50
Just to precise : my installation is completly new (just formated my HDD).

It's strange (and mybe not linked with this one) but on another project with Attiny441 I meet pin mapping problems too. I will do more tests to confirm it,  but it seems analog pin names and digital pin names are "mixed" : if I call pinMode(A7,INPUT) pin 7 and not A7, and 7 is configured as INPUT.

**Comment by SpenceKonde** [comment] 2017-04-24 18:14
digital pin functions (including pinMode) must use the digital pin number, not the analog pin number. I think I have a warning about this. 

A7 (for example) is just #defined as 7 (the analog channel number), so pinMode() can't tell that you meant A7; all it see's is the 7. This isn't ideal, but changing it (by putting an offset on the Ax defines and removing it in analogRead() ) is tricky, because it needs to be done without breaking the ability to read an analog channel other than an analog pin just by passing the channel number (for example, differential inputs, or reading the reference in order to measure the battery voltage). This should be in a separate issue in any case.

**Comment by SpenceKonde** [comment] 2017-05-13 23:19
Updated issue. 

I cannot reproduce issues described above with the pin mapping, though I did fix an issue with a few of the PIN_xn defines.

**Comment by SpenceKonde** [comment] 2017-05-22 20:04
I really want to get this into 1.1.3 - will take a stab at it tonight. This is causing a lot of confusion.

**Comment by battosai30** [comment] 2017-05-23 05:54
Great news :)

**Comment by SpenceKonde** [comment] 2017-06-05 04:20
This may fix it for x4, x5, x313, x61, x7, x8 (not x41, 1634 or 828) https://github.com/SpenceKonde/ATTinyCore/tree/FixDigitalAnalogPinNumberIssues

**Comment by SpenceKonde** [comment] 2017-07-06 22:37
Fix for non x41/1634/828 versions tested, other versions written but untested.

**Comment by SpenceKonde** [comment] 2017-07-10 17:28
Fix was tested last night, merged, and will be in 1.1.3

**Closed** 2017-07-10 17:28 UTC
Labels: enhancement

**Comment by sleemanj** [comment] 2017-07-24 11:32
@AriUJ raises a rather good point here...

https://github.com/SpenceKonde/ATTinyCore/commit/778099585d28031b4acfe2598a04c6afeeda5fd6#commitcomment-23258894

as far as I can see (have not actually tested), the current release has all the Ax constants set to 0, so analogRead(Ax) isn't going to work for anything other than channel zero, and digitalRead/Write/pinMode for any Ax will only affect pin 0.
