### ISSUE TITLE
Interrupt

### ISSUE THREAD

**Issue by gioreva** [SpenceKonde/ATTinyCore#697] opened 2022-06-17 08:28 UTC
Interrupt not work.

Tiny85
Button on PB0 (Work on polling)

attachInterrupt(digitalPinToInterrupt(0), VoidInt, RISING);
attachInterrupt(0, VoidInt, RISING);
attachInterrupt(digitalPinToInterrupt(0), VoidInt, LOW;
attachInterrupt(0, VoidInt, LOW;

void VoidInt(void){
  if( ckOn ) resOn;
  else setOn;
}

**Comment by gioreva** [comment] 2022-06-17 08:48
Also SLEEP seems that it doesn't work.

Always absorbs 4.5mA

set_sleep_mode(SLEEP_MODE_PWR_DOWN);
sleep_enable();
delay(100);
sleep_cpu();
sleep_disable();

**Comment by gioreva** [comment] 2022-06-17 09:30
More info, This my include:

#include <avr/sleep.h>
#include <avr/interrupt.h>
#include <avr/wdt.h>
#include <avr/io.h>
#include <avr/power.h>
#include <util/atomic.h>

**Comment by gioreva** [comment] 2022-06-17 10:49
If i use

MCUCR = (1 << SE) | (1 << SM1); 

instead of

set_sleep_mode(SLEEP_MODE_PWR_DOWN);

Sleep work well.

**Comment by SpenceKonde** [comment] 2022-06-22 21:27
attachInterrupt() works only with INTn interrupts. 

That's pin 2 (PB2), not pin 0. So digitalPinToInterrupt() is returning NOT_AN_INTERRUPT and so attachInterrupt does nothing, but has no means to notify the user that it was passed an invalid pin. I should probably adapt attachInterrupt() so that if the first argument is determined (by optimizer constant folding) to be constant that is always NOT_AN_INTERRUPT or otherwise garbage, it will fail to compile and tell you that you're passing an invalid interrupt identifier. I do this kind of thing very heavily in my newer cores as i realized how stupid it was that Arduino proper makes no attempt to tell people when code is syntactically valid but obviously wrong or meaningless (ex, analogReference(69) or digitalWrite(100,HIGH), on a device without 100 pins), and how many tools the compiler provides to help out here....

Surprised to hear of the sleep mode issue. I'll look into that - the code behind that is dead simple (also "not my department" - it's avrlibc, and since I use an updated toolchain version for development it may even work if I try to compile it), but it is something so incredibly simple that it really should work... It's not like the MCUCR layout for the tiny85 is different from most tinyAVRs
those functions should resolve to

``` c++
// For readability, the backslashes to escape newlines required in processor macros are omitted. 
// The do { ... } while (0) is a c idiom in preprocessor macros, to work around it's bizarre behavior. to execute the contained block a single time, while functioning correctly with all types 
// of code. Otherwise when a macro with multiple statements in it is treated like a function  problems can arise due to a 
// duplicated semicolon, scope issues that are counterintuitive can arise,, or if the macro code is executed conditionally, but the 
// conditional isn't enclosed in {}'s,.

#define set_sleep_mode(mode) 
do { 
    _SLEEP_CONTROL_REG = ((_SLEEP_CONTROL_REG & ~(_BV(SM0) | _BV(SM1))) | (mode));
} while(0)

#define sleep_enable()
do {
  _SLEEP_CONTROL_REG |= (uint8_t)_SLEEP_ENABLE_MASK;
} while(0)

#define sleep_disable()
do {
  _SLEEP_CONTROL_REG &= (uint8_t)(~_SLEEP_ENABLE_MASK);
} while(0)

#define sleep_cpu()
do {
  __asm__ __volatile__ ( "sleep" "\n\t" :: );
} while(0)

#define sleep_mode()
do {
    sleep_enable();  
    sleep_cpu();     
    sleep_disable(); 
} while (0)
```

Two relevant defines:

``` c++
    // after some #if defined() tests
    #define _SLEEP_CONTROL_REG  MCUCR
    #define _SLEEP_ENABLE_MASK  _BV(SE)
```
and from I/O headers
```
#define SE      5
#define SM1     4
#define SM0     3
#define SLEEP_MODE_PWR_DOWN (0x02<<3)
```

So the net result is that those calls are equivalent to
```
inline __attribute__((always_inline)) void set_sleep_mode(SLEEP_MODE_POWER_DOWN) {
  MCUCR = ((MCUCR & ~(0b00011000 ) | 0b0001000);
}
//Ie, set bit 4, SM1 if it's not set, clear bit 3 if it is set,

inline __attribute__((always_inline)) void sleep_enable() { // 3 clocks: IN ORI OUT - 1<< SE is constant and got folded and gets rendered as or with immediate. 
  MCUCR |= 1 << SE;
}

inline __attribute__((always_inline)) void sleep_disable() { // 3 clocks: IN ANDI OUT - ~(1<< SE) is constant and got folded and gets rendered as and with immediate. 
  MCUCR &= ~(1<<SE);}
}

inline __attribute__((always_inline)) void sleep_cpu() { 
   __asm__ __volatile__ ( "sleep" "\n\t" :: );  // 1 clock (plus wakeup time after wake triggered)
}

void  sleep_mode() { // 7 or 11 clocks. plus the time it takes to wake from sleep. 
    MCUCR |= 1 << SE;
    __asm__ __volatile__ ( "sleep" "\n\t" :: ); 
    MCUCR &= ~(1<<SE);}
}

// this would actually ever so slightly more efficient:
// Will break if the interrupt that wakes from sleep writes to MCUCR - but that is rare in practice, as most "wake from sleep" 
// interrupts are just empty ISRs, and whatever you want it to do on wake immediately follows the instruction to sleep.
// Which people routinely create with ISR(vector) {;}, ie, they're empty interrupts. This takes 23 clocks plus the wakeup time, 
// and 20 bytes. ISR(EMPTY_INTERRUPT); takes 8 clocks (plus wakeup time) and 2 bytes. And once you have one empty ISR, if 
// you want another, ISR_ALIAS(vector, alreadt_empty_vector); takes 8 clocks (plus wake up time) and 0 bytes. 
void  sleep_mode_with_caveat() { // 5 clocks 9 in the rare case that there's no free working register - plus wake time. 10 or 14 bytes. 
    
    uint8_t scratch; //note - it's not initialized, because we immediately overwrite whatever was in it, and initializing it might result
    // in an extra ldi instruction and waste 1 clock/2 bytes.
    __asm__ __volatile__ ( 
              "in %0, _SFR_IO_ADDR(MCUCR);" \n\t"
              "ori %0, 0x20" "\n\t"
              "sleep" "\n\t" 
              "andi %0 0xDF" "\n\t" 
              "out _SFR_IO_ADDR(MCUCR); %0" "\n\t"
              :"+d"(scratch)::
    );
}
```

**Comment by SpenceKonde** [comment] 2022-06-23 06:27
So - my diagnosis is that the attachInterrupt issue is user error, that pin does not support attaching interrupts and the Arudino API does not support pcints. 




That the Arduino API doesn't wrap PCINTS is something we should all be thankful for.  On modern AVRs they got rid of the INTn interrupts, giving most of their features to "pin interrupts" which acted much like PCINTs in banks of 8. Great! But the clowns who write the official Arduino core had to make attachInterrupt work on all pins.... so it has logic to pick which of the up-to-8 interrupts to call. 

The end result? If any user code or library referenced attachInterrupt(), it would pull in an ISR for EVERY PIN INTERRUPT, and you could no longer make one that executed in 8 or even 19 clock cycles, but rather one that executed in 50-100 clocks, even for an empty interrupt, AND because it glommed onto every pin vector, you can't even manually define an interrupt that will execute quickly. It is an unholy abomination.

attachInterrupt has the same latency problem by the way, though not as severely. 

```
MCUCR |= MCUCR & ((1<<ISC1) | (1 <<ISC0)) | (0, 1, 2 or 3);
// 0 = LOW LEVEL, 1 = any edge, 2 = falling edge 3 = rising edge. 

ISR(some_vect) {
  /* code, but no function calls that won't be inlined */
}
````
is up to 29 clocks slower to enter and 28 clocks slower on exit than
```
attachInterrupt(myisr, (LOW, RISING, FALLING or CHANGE));
// This is actually probably understating the inefficiency - it doesn';t
void myisr() {
  /* the same exact code as the interrupt above */
}
```
because to comply with C the ABI, it has to push every call used register onto the stack (2 clocks per register, and there are 14 of them - but r0 and r1 (temp_reg and zero_reg) get pushed for any non-EMPTY_INTERRUPT. non-NAKED_INTERRUPT), load two bytes into the Z register and icall that function pointer (5 clocks), then at the end, restore all those values by popping them off the stack.  (says right in the datasheet not to call functions from within ISRs because of the performance impact...)

On the modern AVRs. I eventually got so f'ing fed up with it, because libraries would use attachInterrupt and then you couldn't manually define pin interrupts, that as of mTC 2.5.0 and DxC 1.4.0, I replaced the 1 file with up to 7 ISRs (for each port present on the part) with 1 file per port, so they wouldn't get pulled in unless something referenced something else in that file, and then put in trivial functions attachAEnable() attachBenable() which would get optimized away because they were do-nothing functions, but were sufficient to pull in the ISR, and replaced each ISR with a NAKED_ISR that pushed a single register onto the stack (to make room), then loaded 2*port number via LDI into that register, and then called a ((naked))((used)) function defined back in WInterrupts (since everything is naked, no pushing or popping was done automatically), and I then manually push r0, load and push the status register, clear r1. and push the necessary registers to call a function, plus the one needed to make the pin detection logic work, implemented that in assembly to loop over the port's interrupt flags, and icall the appropriate pointer (unless it was a null pointer), and then restore the call used registers and SREG and return from the interrupt. 

While 2.5.0/1.4.0 worked in my easy test, It took until 2.5.11 and 1.4.10 before it worked correctly for all cases. Those cores have a tools menu to select either the new implementation, but with all the attach enable functions called at startup, (the default), only enable the interrupts that the user manually enables, or fall back to the old version (because I realized the chance that it would actually work on intial release was just about 0%). I did something very similar to that for the USART interrupts too not for speed (because there wasn't an advantage there) but because it avoided duplicating the ISR code for each USART (and DA/DB parts have up to 6, while tinyAVR parts can have 2 USARTs on parts with as little as 4k of flash.

**Comment by gioreva** [comment] 2022-06-23 10:50
I have problems understanding everything you wrote, both for my bad English and because I have very little time.

My project now works well in this way.

`MCUCR = (1 << SE) | (1 << SM1);     //  set_sleep_mode(SLEEP_MODE_PWR_DOWN);`

This only for wake up:
```
  PCMSK = 1;  // Pin change interrupt    (1 << PCINT0)
  GIMSK = (1 << PCIE);    // Pin change enable
```

This not work, i have lost 20uA
Marking of my chip is T85 20UBRK 11918M
If B is relise code, need relise from C 
```
  noInterrupts();
  byte reg1 = MCUCR | (1<<BODS) | (1<<BODSE);
  byte reg2 = MCUCR & ~(1<<BODSE);
  MCUCR = reg1;
  MCUCR = reg2;
  interrupts();
```

```
void Off ( void ){
  analogReference(DEFAULT);
  ClearBit(ADCSRA,ADEN);    // ADC off,  this save 200uA
  resOn;
  sleep_cpu();  
  SetBit(ADCSRA,ADEN);      // ADC  on
  analogReference(INTERNAL);
}
ISR(PCINT0_vect){  // Pin Change interrupt
}
```

Total consumption is 20uA with on BOD, and 0uA with off BOD

**Comment by SpenceKonde** [comment] 2022-06-30 11:01
sorry - I didn't realize you weren't a native english speaker, and wrote a lot more than was needed.... 

I don't know why set_sleep_mode(SLEEP_MODE_POWER_DOWN) isn't working. It should be identical to 
MCUCR |= 1<< SM1;
MCUCR &= ~(1<<SM0); // this line isn't needed unless you use other sleep modes. 
and sleep_enable() should be the same as 
MCUCR |= 1<<SE;

You cannot *ever* wake on `RISING` or `FALLING` on a classic AVR, only PCINT on any pin, or LOW or CHANGE on PB2 (the INT0 pin). Without the peripheral clock running (which uses a lot of power and hence is turned off in power-down-sleep),  they can only detect changes (and low level on one pin); they can't distinguish between rising and falling edges.


Regarding the BODSE/BODS bits.... I just read that section of the datasheet several times. That is one of the weirdest and stupidest things I've seen in AVRs, and it is very poorly described. It sounds to me like the timed sequence requires you to do a three step timed sequence. I don't know of any other 3-step timed sequences in AVRs. 
1. Set BODSE and BODS
2. Clear BODSE but not BODS within 4 clocks
3. enter sleep mode within 3 clocks of doing that. 

This is unique to BODS on late-model classic AVR. There is a wrapper around it in sleep.h.... albeit a really unhelpful one that still requires 4 calls to put the chip to sleep. This should do it...


```
void sleep_no_bod() {
  sleep_enable();
  cli(); // I don't know if this will work - sei would have to be called between sleep_bod_disable() and sleep_cpu(),
  sleep_bod_disable(); //Can't be done with interrupts disabled, because the sleep instruction is ALSO part of timed sequence
  sei(); //must enable interrupts before executing sleep_cpu. If it doesn't work with cli() and sei(), try removing those,
  sleep_cpu();
  sleep_disable();
}
```
This may work, or it may fail sometimes becuase of an interrupt hitting in sleep_bod_disable, which would make the timed sequence expire before BODS auto-clears
```
void sleep_no_bod2() {
  sleep_enable();
  sleep_bod_disable(); //Can't be done with interrupts disabled, because the sleep instruction is ALSO part of timed sequence
  sleep_cpu();
  sleep_disable();
}
```
If the first version above doesn't work, but the second does, it sounds like there's not even one clock cycle to spare to reenable interrupts between the end if sleep_bod_disable, and sleep_cpu() - in that case you may need to disable all other interrupts you have enabled that aren't the one you are waking the chip with. then reenable them on wake, The example below assumes that the only other interrupt is Timer0 OVF (timer0 overflow, used for millis)
```
void sleep_no_bod3() {
  sleep_enable();
  TIMSK &= ~(1<<TOIE0); // disable millis timer interrupt (it doesn't count while asleep anyway, this is to make sure it can't interrupt the timed sequence
  // need to to the same thing for any other interrupts except the one that wakes the chip
  sleep_bod_disable(); //Can't be done with interrupts disabled, because the sleep instruction is ALSO part of timed sequence
  sleep_cpu();
  TIMSK &= ~(1<<TOIE0); //we are awake now, turn millist timer interrupt back on to resume timekeeping 
  sleep_disable();
}
```

Or just select BOD disabled and "burn bootloader" and turn off BOD entirely? 

If you really need BOD, then this gets hard, because BODS and BODSE are "working as intended", but that doesn't mean it's not hard to use. 

Assuming I'm understanding the datasheet correctly, that's maybe the #2 worst "intended behavior" I'm aware of for an AVR (The UPDI programming protocol for Dx-series parts is #1 is IMHO worse, because at least the BODS/BODSE behavior is documented (if poorly), while the with programming DX (namely, that the updi command "sts", with 16 bit address instead of full 24-bit address length doesn't assume 0 for the high byte unless you haven't set the pointer, but the datasheet say sthe pointer is only used for UPDI_ST.) 

They eventually realized that the method for disabling BOD like that sucked - The last 4 classic tinyAVRs released (841, 441, 828, and 1634) removed that feature entirely, and replaced it with a few bits in the fuses to separate;y configure BOD in active and sleep modes. 

As for finding die rev:
There are three lines of text that are needed to fully identify a chip. 
The first is the T85 20UBRK, which identifies the part number. 
The next is the a date-and-fab code that tells you where and when it was made
The third is 6 characters ending in the die rev, which is a letter. Usually the first three characters are 196, 354 or 355. and the last one is the die rev. I don't know what any of the other characters in that string mean. 

All t85's produced after 2011 (or maybe earlier) were the Rev. C so it's unlikely that you have a Rev. B. but the numbers you posted don't include the revision - there's no Rev  K or rev M. 

If the chip is a DIP-8, or wide SOIC package (body 5.x mm wide), the the revision ID line is located on the _bottom_ of the chip, while on the QFN package, all three lines are _top_. On narrow SOIC/SOP packages, it is not marked. There is no way to read the revision from software on the t85, so on parts without the third line the only way to know for sure is create a ticket with Microchip support telling them the numbers you told me, and ask what revision it is. I would say something like "Can you confirm what the die revision of this tiny85 marked "T85 20UBRK 11918M" is? I have been having trouble disabling BOD before entering sleep and want to make sure I'm not actually using a Rev C part. thanks". 

Don't mention Arduino - they know we're not going to buy millions of dollars of chips for a company, and we seem to get low priority with them. 


Newer devices (parts first released in 2016 and later, what I call modern AVRs - the ones supported by megaTinyCore and DxCore) have all new peripherals, and they mostly fix these issues: You can read die rev from software, controlling whether the BOD is enabled in sleep from software only requires a normal timed write sequence, instead of a double timed write sequence.

**Closed as completed** 2022-06-30 11:01 UTC
Labels: not a bug / technical assistance
