### ISSUE TITLE
ATtinyCore installation failed due to expired tls certificate for azduino.com

### ISSUE THREAD

**Issue by schorsch3000** [SpenceKonde/ATTinyCore#819] opened 2023-11-09 17:09 UTC
Title says it all basically.
While installing ATtinyCore 1.5.2 in Arduino 2.2.1 (using the rename package_drazzy.json workaround) ill get the following error in the console:
```
Tool arduino:avr-gcc@7.3.0-atmel3.6.1-arduino7 already installed
Downloading packages
arduino:avrdude@6.3.0-arduino18
ATTinyCore:micronucleus@2.5-azd1b
Failed to install platform: 'ATTinyCore:avr:1.5.2'.
Error: 2 UNKNOWN: Get "https://azduino.com/bin/micronucleus/micronucleus-cli-2.5-azd1-x86_64-linux-gnu.tar.bz2": tls: failed to verify certificate: x509: certificate has expired or is not yet valid: current time 2023-11-09T18:03:41+01:00 is after 2023-10-26T15:15:54Z

```

**Comment by roger-tannous** [comment] 2023-11-09 20:44
It seems that the SSL certificate (from Let's Ecrypt) is expired.

I have faced the same problem, and fixed it like the below (as a temporary arrangement)::

On Linux/Mac, 

```
sed -ri "s/https\:\/\/([^\"]+)/http\:\/\/\1/g" ~/.arduino15/package_drazzy.com_index.json

sed -ri "s/https\:\/\/([^\"]+)/http\:\/\/\1/g" ~/.arduino15/package_drazzy.json
```


On Windows, just edit the file(s) and change https to http for all URLs that are double quoted.

**Comment by roger-tannous** [comment] 2023-11-09 20:49
It seems this issue has been handled in a different way previously, here's [the link](https://forum.arduino.cc/t/2-2-1-board-manager-download-additional-boards/1182930/2)

**Comment by per1234** [comment] 2023-11-17 16:05
Duplicate of https://github.com/SpenceKonde/ATTinyCore/issues/815

**Comment by samster395** [comment] 2023-11-27 20:14
Taken from https://forum.arduino.cc/t/2-2-1-board-manager-download-additional-boards/1182930/28

The workaround will be to manually download the tool archive (the archive download URLs can be extracted from [the package index file 12](https://drazzy.com/package_drazzy.com_index.json)) and then place it in the Boards Manager download cache. Arduino IDE checks for the file in the cache before attempting to download it from the Internet, so if you have manually placed the file in that location, you avoid the problematic download that causes the ATTinyCore installation to fail.

1. Download the ATTinyCore:micronucleus@2.5-azd1b Archive File
Unfortunately you will likely find that attempting to download this file via the browser is not very user friendly. For security reasons, the browser will try to strongly discourage from downloading it and you will have to make some efforts to overcome its resistance.

This is the download URL:

If you are using Windows:
`http://azduino.com/bin/micronucleus/micronucleus-cli-2.5-azd1b-x86_64-mingw32.zip`
If you are using Linux x86:
`http://azduino.com/bin/micronucleus/micronucleus-cli-2.5-azd1-x86_64-linux-gnu.tar.bz2`
If you are using Linux ARM:
`http://azduino.com/bin/micronucleus/micronucleus-cli-2.5-azd1-arm-linux-gnueabihf.tar.bz2`
If you are using macOS:
`http://azduino.com/bin/micronucleus/micronucleus-cli-2.5-azd1-x86_64-apple-darwin.tar.bz2`
2. Add the Downloaded File to the Boards Manager Cache
After you manage to download the file, copy it to the following folder:

If you are using Windows:
`C:\Users\<username>\AppData\Local\Arduino15\staging\packages\`
(Where <username> is your Windows username)

If you are using Linux:
`/home/<username>/.arduino15/staging/packages/`
(Where <username> is your Linux username)

If you are using macOS:
`/Users/<username>/Library/Arduino15/staging/packages/`
(Where <username> is your macOS username)

3. Install ATTinyCore
Now try installing ATTinyCore via the Arduino IDE Boards Manager again. The installation should now be successful.

**Closed as completed** 2023-12-20 21:05 UTC
Labels: duplicate

**Comment by schorsch3000** [comment] 2023-12-21 09:29
How is this completed?
Nothing changed...

**Comment by hmeijdam** [comment] 2023-12-21 09:55
> How is this completed? Nothing changed...

Because it's a duplicate report of an already existing issue. That's what the "duplicate" label means.

![image](https://github.com/SpenceKonde/ATTinyCore/assets/9595465/a22c49a9-41ae-45dd-837f-95adfa324476)

**Comment by schorsch3000** [comment] 2023-12-21 10:07
![image](https://github.com/SpenceKonde/ATTinyCore/assets/2485762/f3231600-1e37-4ac0-bece-961be0d9d26d)

There are options :-)
