### ISSUE TITLE
Any chance of supporting ATTINY814

### ISSUE THREAD

**Issue by whmountains** [SpenceKonde/ATTinyCore#189] opened 2018-01-21 20:24 UTC
Is there any technical limitation preventing ATTinyCore from being ported to this MCU?  It has some nice low-power features that I'd like to use.

**Comment by SpenceKonde** [comment] 2018-01-21 20:42
Duplicate of #174. 

Supporting these chips requires rewriting every single function that inferfaces with chip features in any way - serial, digitalWrite/Read/pinMode, PWM, SPI, I2C, and so on - EVERYTHING. These parts might as well be a different architecture entirely.

**Closed by SpenceKonde** 2018-01-21 20:42 UTC

**Comment by SpenceKonde** [comment] 2019-06-21 04:17
https://github.com/SpenceKonde/megaTinyCore This is happening now. Still not quite ready, but progressing quickly, follow that repo for updates
