### ISSUE TITLE
ATTiny161* support?

### ISSUE THREAD

**Issue by jstjst** [SpenceKonde/ATTinyCore#181] opened 2017-12-09 19:16 UTC
Hi,

i just have a question about the newer ATTiny devices: Do you plan to support the ATTiny 1614/1616/1617?

**Comment by SpenceKonde** [comment] 2017-12-10 10:14
These are the "new" (ie, PIC-like) AVRs; a huge amount of work is required to support them (right down to stuff like digitalWrite() ). New software architecting work is also needed to figure out the appropriate wrapper for the new pin remapping system. 

Closed as duplicate of #174 - everything said there applies to these chips as well.

**Closed by SpenceKonde** 2017-12-10 10:14 UTC
Labels: duplicate

**Comment by SpenceKonde** [comment] 2019-06-21 04:17
https://github.com/SpenceKonde/megaTinyCore This is happening now. Still not quite ready, but progressing quickly, follow that repo for updates

**Comment by sleemanj** [comment] 2019-06-22 02:21
Noticed in a reddit post
https://tinycore.dev/
https://github.com/xukangmin/TinyCore

**Comment by SpenceKonde** [comment] 2019-06-22 02:29
my megaTinyCore is close to supporting all of the 1-series and 0-series megaAVR attiny parts. Check out the link I posted above. It's mighty close. Expecting to be doing 1.0.0 release this weekend.
