### ISSUE TITLE
problem error

### ISSUE THREAD

**Issue by anwfeb** [SpenceKonde/ATTinyCore#845] opened 2024-02-19 02:32 UTC
please check your [url](Error downloading https://drazzy.com/package_drazzy.com_index.json)

**Comment by hmeijdam** [comment] 2024-02-19 07:20
Please check this [workaround](https://github.com/SpenceKonde/megaTinyCore/issues/1059#issuecomment-1950286469)

**Comment by SpenceKonde** [comment] 2024-07-28 20:32
fixed now

**Closed as completed by SpenceKonde** 2024-07-28 20:32 UTC

**Comment by gnif** [comment] 2024-11-08 10:32
And it's broken again. It's a let's encrypt cert, have you forgot to setup your cronjob to renew the cert?

**Comment by per1234** [comment] 2024-11-08 10:48
The current occurrence of the problem is being tracked at https://github.com/SpenceKonde/ATTinyCore/issues/885. Check **@SpenceKonde**'s comments on that thread for an update on the situation.
