### ISSUE TITLE
Attiny core 1.5.2

### ISSUE THREAD

**Issue by smdg49** [SpenceKonde/ATTinyCore#817] opened 2023-11-05 03:42 UTC
http://drazzy.com/package_drazzy.com_index.json
added to new installation of arduino ide 2.x .
Does not show any of the attiny core boards in the boards manager.
Does work with my existing installation, but not on any new install.
Attempted on multiple devices.
Other boards added to "additional boards manager URLs" in arduino IDE do work but not http://drazzy.com/package_drazzy.com_index.json

**Comment by per1234** [comment] 2023-11-17 16:05
Duplicate of https://github.com/SpenceKonde/ATTinyCore/issues/802. The cause is explained here: https://github.com/SpenceKonde/ATTinyCore/issues/802#issuecomment-1751882383 (note that bug has already been fixed, and is in the process of being pulled into Arduino IDE right now: https://github.com/arduino/arduino-ide/pull/2281).

**Closed as completed** 2023-12-20 21:09 UTC
Labels: duplicate, Not our bug
